import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Navbar from "./components/Navbar";
import SocialMedia from "./components/SocialMedia";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Fondo de imagen aplicado en body */}
      <body className={`${inter.className} bg-layout`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SocialMedia />
          <div className="my-10 mx-16 bg-background rounded-4xl">
            <Navbar />
            <main className="max-w-2xl mx-auto px-4">{children}</main>
          </div>
          {/* </div> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
